source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'HuntVision' do

pod 'Alamofire', '~> 1.2'
pod 'Mantle'
pod 'MBProgressHUD'
pod 'TSMessages'
pod 'RMPickerViewController'
end

target 'HuntVisionTests' do

end

